-- Turrute v9: curated Vestfold trail layer
-- Rådata fra Turrutebasen beholdes i raw_turruter, men publiseres ikke direkte som app-turer.
-- Denne migrasjonen etablerer et kuratert første datasett som faktisk gir mening i UI/kart.

alter table public.trails add column if not exists source_category text;
alter table public.trails add column if not exists published boolean not null default true;
alter table public.trails add column if not exists is_demo boolean not null default false;
alter table public.trails add column if not exists trail_mode text;

create index if not exists trails_published_idx on public.trails (published);
create index if not exists trails_source_category_idx on public.trails (source_category);
create index if not exists trails_trail_mode_idx on public.trails (trail_mode);

-- Ikke vis råimporterte Turrutebasen-segmenter som ferdige turforslag.
update public.trails
set published = false,
    curated = false,
    data_quality_note = coalesce(data_quality_note, '') || ' v9: Skjult fra produktvisning. Rå Turrutebasen-segmenter brukes som rågrunnlag, ikke ferdige turforslag.'
where source in ('kartverket_turrutebasen_wfs', 'kartverket_turrutebasen_live')
  and coalesce(published, true) = true;

-- Fjern eldre demo/null-kilder fra app-tabellen. Kuraterte rader under upsertes på nytt.
delete from public.trails
where source is null or source in ('demo', 'local-json');

insert into public.trails (id, slug, name, municipality, area, distance_km, estimated_minutes, difficulty, route_type, trail_mode, surface_type, elevation_gain_m, suitable_stroller, suitable_baby_carrier, suitable_wheelchair, suitable_easy_walk, suitable_children, suitable_dog, has_parking, has_toilet, has_viewpoint, tags, description, image_url, lat, lng, route_geojson, source, source_category, source_route_id, curated, published, is_demo, accessibility_verified_at, data_quality_note)
values
  ('verdens-ende-kort-tur', 'verdens-ende-kort-tur', 'Verdens Ende kort tur', 'Færder', 'Tjøme', 1.6, 35, 'Lett', 'Kort rundtur', 'walking', 'Grus, asfalt og svaberg', 20, true, true, true, true, true, true, true, true, true, array['Kyst','Utsikt','Tilgjengelig','Kort tur']::text[], 'Kort og vakker tur ytterst mot havet. Passer godt når du vil ha stor naturopplevelse uten lang distanse.', null, 59.0529, 10.4106, '{"type": "LineString", "coordinates": [[10.4106, 59.0529], [10.4145, 59.0537], [10.4167, 59.0518], [10.4122, 59.0508], [10.4106, 59.0529]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('bokeskogen-rundtur', 'bokeskogen-rundtur', 'Bøkeskogen rundtur', 'Larvik', 'Larvik sentrum', 2.5, 45, 'Lett', 'Rundtur', 'walking', 'Grusvei og bred sti', 35, true, true, false, true, true, true, true, true, false, array['Skog','Skygge','Barn','Lett å gå']::text[], 'Rolig rundtur i den historiske bøkeskogen. Fin for småbarn, hundelufting og en lavterskel tur nær sentrum.', null, 59.0556, 10.0351, '{"type": "LineString", "coordinates": [[10.0351, 59.0556], [10.0392, 59.0578], [10.044, 59.0555], [10.042, 59.0521], [10.036, 59.0527], [10.0351, 59.0556]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('karljohansvern-runden', 'karljohansvern-runden', 'Karljohansvern-runden', 'Horten', 'Karljohansvern', 3.1, 60, 'Lett', 'Rundtur', 'walking', 'Asfalt og grus', 15, true, true, true, true, true, true, true, true, true, array['Kyst','Kultur','Kafé i nærheten','Tilgjengelig']::text[], 'Bynær runde med sjø, kulturmiljø og korte avstikkere. God demo-tur fordi start/slutt er enkel og ruten er lett å forstå.', null, 59.4263, 10.4844, '{"type": "LineString", "coordinates": [[10.4844, 59.4263], [10.4908, 59.4285], [10.4955, 59.4248], [10.4912, 59.4209], [10.4848, 59.4222], [10.4844, 59.4263]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('borrehaugene-kultursti', 'borrehaugene-kultursti', 'Borrehaugene kultursti', 'Horten', 'Borre', 2.2, 45, 'Lett', 'Rundtur', 'walking', 'Grus og gress', 25, true, true, true, true, true, true, true, false, true, array['Kultur','Åpent landskap','Barn','Historie']::text[], 'Lett tur i åpent historisk landskap. Passer godt som kort familietur med god plass og enkel orientering.', null, 59.3814, 10.4686, '{"type": "LineString", "coordinates": [[10.4686, 59.3814], [10.4732, 59.3832], [10.4768, 59.3802], [10.4725, 59.3775], [10.4679, 59.3785], [10.4686, 59.3814]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('ilene-fugletarn', 'ilene-fugletarn', 'Ilene naturreservat til fugletårnet', 'Tønsberg', 'Ilene', 2.0, 40, 'Lett', 'Tur-retur', 'walking', 'Grus og tredekke', 5, true, true, true, true, true, false, true, false, true, array['Fugletitting','Flatt','Naturreservat','Tilgjengelig']::text[], 'Flat og rolig tur med fugletårn og natur tett på byen. God for barnevogn og korte pauser underveis.', null, 59.2797, 10.3716, '{"type": "LineString", "coordinates": [[10.3716, 59.2797], [10.3675, 59.2804], [10.3637, 59.2812], [10.3606, 59.2816]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('slottsfjellet-rundt', 'slottsfjellet-rundt', 'Slottsfjellet rundt', 'Tønsberg', 'Sentrum', 1.8, 40, 'Lett / middels', 'Rundtur', 'walking', 'Asfalt, grus og sti', 55, false, true, false, true, true, true, true, true, true, array['Utsikt','Kultur','Kort tur','Bytur']::text[], 'Kort bynær tur med historie og utsikt. Litt stigning gjør den best for gående barn eller bæremeis fremfor tung barnevogn.', null, 59.2699, 10.4073, '{"type": "LineString", "coordinates": [[10.4073, 59.2699], [10.4104, 59.2714], [10.4132, 59.2695], [10.4111, 59.2672], [10.4079, 59.2677], [10.4073, 59.2699]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('molen-kysttur', 'molen-kysttur', 'Mølen kysttur', 'Larvik', 'Brunlanes', 2.3, 50, 'Lett / middels', 'Tur-retur / rundtur', 'walking', 'Sti og rullestein', 25, false, true, false, false, true, true, true, true, true, array['Havutsikt','Geologi','Bæremeis','Ikke barnevogn hele veien']::text[], 'Spektakulær kysttur med rullestein og åpent hav. Best med bæremeis eller større barn, ikke som primær barnevogntur.', null, 58.9691, 9.8261, '{"type": "LineString", "coordinates": [[9.8261, 58.9691], [9.8325, 58.9698], [9.8362, 58.9675], [9.8314, 58.9658], [9.8261, 58.9691]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('stavern-kyststi-kort', 'stavern-kyststi-kort', 'Stavern kyststi kort runde', 'Larvik', 'Stavern', 3.4, 70, 'Lett / middels', 'Tur-retur', 'walking', 'Kyststi, grus og svaberg', 45, false, true, false, true, true, true, true, false, true, array['Kyststi','Sjøutsikt','Barn','Bæremeis']::text[], 'Kort kyststi-etappe med sjøutsikt og fine stopp. Velg denne når dere tåler litt ujevnt underlag.', null, 58.9992, 10.0344, '{"type": "LineString", "coordinates": [[10.0344, 58.9992], [10.0392, 58.9968], [10.0451, 58.9952], [10.0494, 58.9966]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('holmestrand-fjordpromenade', 'holmestrand-fjordpromenade', 'Holmestrand fjordpromenade', 'Holmestrand', 'Sentrum', 2.6, 45, 'Lett', 'Tur-retur', 'walking', 'Asfalt og promenade', 10, true, true, true, true, true, true, true, true, true, array['Promenade','Fjord','Tilgjengelig','Kort tur']::text[], 'Flat fjordtur med enkel adkomst. God for rullestol, barnevogn og korte turer etter jobb eller barnehage.', null, 59.4872, 10.3147, '{"type": "LineString", "coordinates": [[10.3147, 59.4872], [10.3194, 59.4893], [10.3245, 59.4907], [10.3292, 59.4918]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('eidsfoss-kultursti', 'eidsfoss-kultursti', 'Eidsfoss kultursti', 'Holmestrand', 'Eidsfoss', 2.4, 50, 'Lett', 'Rundtur', 'walking', 'Grus og asfalt', 20, true, true, false, true, true, true, true, false, true, array['Kultur','Vann','Familievennlig','Rolig']::text[], 'Koselig tur med kulturmiljø, vann og korte avstander. Passer fint som søndagstur med barn.', null, 59.5935, 10.0362, '{"type": "LineString", "coordinates": [[10.0362, 59.5935], [10.0415, 59.5948], [10.0442, 59.5916], [10.0395, 59.5898], [10.0362, 59.5935]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('hjertnesstranda-promenade', 'hjertnesstranda-promenade', 'Hjertnesstranda promenade', 'Sandefjord', 'Sentrum', 2.1, 40, 'Lett', 'Tur-retur', 'walking', 'Asfalt og promenade', 8, true, true, true, true, true, true, true, true, true, array['Promenade','Strand','Tilgjengelig','Sentrum']::text[], 'Lavterskel tur langs vannet nær sentrum. God for barnevogn, rullestol og en kort luftetur.', null, 59.1312, 10.2264, '{"type": "LineString", "coordinates": [[10.2264, 59.1312], [10.2303, 59.1304], [10.2345, 59.1295], [10.2392, 59.1288]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('midtasen-rundtur', 'midtasen-rundtur', 'Midtåsen rundtur', 'Sandefjord', 'Midtåsen', 2.0, 45, 'Lett / middels', 'Rundtur', 'walking', 'Grus, sti og parkvei', 45, false, true, false, true, true, true, true, false, true, array['Utsikt','Park','Kort tur','Barn']::text[], 'Kort tur i park- og skogpreg med utsikt. Noe stigning gjør den best for gående eller bæremeis.', null, 59.1196, 10.2052, '{"type": "LineString", "coordinates": [[10.2052, 59.1196], [10.2093, 59.1212], [10.2125, 59.1191], [10.2101, 59.1164], [10.2052, 59.1196]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('bugardsparken-rundtur', 'bugardsparken-rundtur', 'Bugårdsparken rundtur', 'Sandefjord', 'Bugården', 1.9, 35, 'Lett', 'Rundtur', 'walking', 'Asfalt og grus', 5, true, true, true, true, true, true, true, true, false, array['Park','Flatt','Barn','Tilgjengelig']::text[], 'Enkel park- og nærtur med kort avstand, flatt underlag og mange muligheter for pause.', null, 59.1363, 10.2017, '{"type": "LineString", "coordinates": [[10.2017, 59.1363], [10.2055, 59.1377], [10.2084, 59.1351], [10.2044, 59.1335], [10.2017, 59.1363]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('teieskogen-runde', 'teieskogen-runde', 'Teieskogen runde', 'Færder', 'Nøtterøy', 2.7, 55, 'Lett', 'Rundtur', 'walking', 'Grusvei og skogssti', 30, true, true, false, true, true, true, true, false, false, array['Skog','Nærtur','Barn','Lett å gå']::text[], 'Enkel skogstur nær boligområder. Fin for hverdagslogistikk når dere bare trenger en tur som fungerer.', null, 59.2515, 10.4256, '{"type": "LineString", "coordinates": [[10.4256, 59.2515], [10.4312, 59.2534], [10.4361, 59.2506], [10.4321, 59.2478], [10.426, 59.2488], [10.4256, 59.2515]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('moutmarka-kort-runde', 'moutmarka-kort-runde', 'Moutmarka kort runde', 'Færder', 'Tjøme', 3.2, 70, 'Lett / middels', 'Rundtur', 'walking', 'Sti og kystterreng', 45, false, true, false, false, true, true, true, false, true, array['Kyst','Naturreservat','Bæremeis','Utsikt']::text[], 'Kystnær runde med naturpreg og utsikt. Velg bæremeis eller gående barn, ikke barnevogn.', null, 59.0798, 10.3946, '{"type": "LineString", "coordinates": [[10.3946, 59.0798], [10.4008, 59.0815], [10.4048, 59.0787], [10.3994, 59.0756], [10.3946, 59.0798]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('asgardsstrand-promenade', 'asgardsstrand-promenade', 'Åsgårdstrand strandpromenade', 'Horten', 'Åsgårdstrand', 2.0, 40, 'Lett', 'Tur-retur', 'walking', 'Asfalt og grus', 10, true, true, true, true, true, true, true, true, true, array['Kyst','Promenade','Tilgjengelig','Kort tur']::text[], 'Rolig promenade med sjøutsikt og enkel adkomst. God første tur i appen fordi den er lett å forstå og lett å gjennomføre.', null, 59.3498, 10.4674, '{"type": "LineString", "coordinates": [[10.4674, 59.3498], [10.4714, 59.3478], [10.4758, 59.3459], [10.4795, 59.3442]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('folehavna-kysttur', 'folehavna-kysttur', 'Folehavna kysttur', 'Sandefjord', 'Vesterøya', 3.0, 65, 'Lett / middels', 'Tur-retur', 'walking', 'Sti og kystterreng', 40, false, true, false, false, true, true, true, false, true, array['Kyst','Utsikt','Bæremeis','Ikke barnevogn']::text[], 'Flott kysttur på Vesterøya med åpent landskap og utsikt. Ikke primært for barnevogn, men fin med bæremeis.', null, 59.0558, 10.2132, '{"type": "LineString", "coordinates": [[10.2132, 59.0558], [10.2188, 59.0565], [10.2225, 59.0535], [10.217, 59.0514]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.'),
  ('goksjo-kort-naturtur', 'goksjo-kort-naturtur', 'Goksjø kort naturtur', 'Sandefjord', 'Goksjø', 3.6, 75, 'Lett / middels', 'Tur-retur', 'walking', 'Grusvei og sti', 35, false, true, false, true, true, true, true, false, true, array['Vann','Natur','Barn','Rolig']::text[], 'Kort naturtur ved Goksjø-området. Egner seg når dere vil ha vann og ro, men ikke en altfor lang tur.', null, 59.1744, 10.1438, '{"type": "LineString", "coordinates": [[10.1438, 59.1744], [10.1492, 59.1767], [10.1548, 59.1754], [10.1587, 59.1729]]}'::jsonb, 'curated_vestfold_v1', 'curated_tour', null, true, true, false, null, 'Kuratert førsteversjon for MVP. Rutegeometri er for produktdemo og må kvalitetssikres mot lokale kartdata/feltdata før offentlig lansering.')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  municipality = excluded.municipality,
  area = excluded.area,
  distance_km = excluded.distance_km,
  estimated_minutes = excluded.estimated_minutes,
  difficulty = excluded.difficulty,
  route_type = excluded.route_type,
  trail_mode = excluded.trail_mode,
  surface_type = excluded.surface_type,
  elevation_gain_m = excluded.elevation_gain_m,
  suitable_stroller = excluded.suitable_stroller,
  suitable_baby_carrier = excluded.suitable_baby_carrier,
  suitable_wheelchair = excluded.suitable_wheelchair,
  suitable_easy_walk = excluded.suitable_easy_walk,
  suitable_children = excluded.suitable_children,
  suitable_dog = excluded.suitable_dog,
  has_parking = excluded.has_parking,
  has_toilet = excluded.has_toilet,
  has_viewpoint = excluded.has_viewpoint,
  tags = excluded.tags,
  description = excluded.description,
  image_url = excluded.image_url,
  lat = excluded.lat,
  lng = excluded.lng,
  route_geojson = excluded.route_geojson,
  source = excluded.source,
  source_category = excluded.source_category,
  source_route_id = excluded.source_route_id,
  curated = excluded.curated,
  published = excluded.published,
  is_demo = excluded.is_demo,
  accessibility_verified_at = excluded.accessibility_verified_at,
  data_quality_note = excluded.data_quality_note,
  updated_at = now();

comment on column public.trails.published is 'True when the trail is visible in app/product views.';
comment on column public.trails.source_category is 'High-level import/source category such as curated_tour or raw route type.';
